@URL = http://localhost:5284

###
GET {{URL}}/comments
Accept: application/json

### 
GET {{URL}}/comments/1
Accept: application/json

### 
POST {{URL}}/comments
Content-Type: application/json

{
  "name": "Katya",
  "email": "katya@yandex.com",
  "body": "Is Katya Vlasova test1",
  "postId": 1
}

###
PATCH {{URL}}/comments/6
Content-Type: application/json

{
  "name": "Joker",
  "email": "katya@yandex.com",
  "body": "Is Joker Katya",
  "postId": 1
}

### 
DELETE {{URL}}/comments/5